// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab2;

#nullable disable

namespace lab2.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20251203010912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("lab2.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("lab2.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("lab2.Models.StudentCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentCards");
                });

            modelBuilder.Entity("lab2.Models.Professor", b =>
                {
                    b.HasBaseType("lab2.Models.Person");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.ToTable("Professors", (string)null);
                });

            modelBuilder.Entity("lab2.Models.Student", b =>
                {
                    b.HasBaseType("lab2.Models.Person");

                    b.Property<DateTime>("EndOfTraining")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartOfTraining")
                        .HasColumnType("TEXT");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("lab2.Models.Course", b =>
                {
                    b.HasOne("lab2.Models.Professor", "Professor")
                        .WithMany("Courses")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("lab2.Models.StudentCard", b =>
                {
                    b.HasOne("lab2.Models.Student", "Student")
                        .WithOne("StudentCard")
                        .HasForeignKey("lab2.Models.StudentCard", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("lab2.Models.Professor", b =>
                {
                    b.HasOne("lab2.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("lab2.Models.Professor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lab2.Models.Student", b =>
                {
                    b.HasOne("lab2.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("lab2.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("lab2.Models.Professor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("lab2.Models.Student", b =>
                {
                    b.Navigation("StudentCard");
                });
#pragma warning restore 612, 618
        }
    }
}
